/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CINETIX;
import com.toedter.calendar.JDateChooser;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
/**
 *
 * @author Daffa
 */
public class AdminFrame extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public AdminFrame() {
        initComponents();
        JDateChooser tanggalLahir = new JDateChooser();
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablepembelian = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        Update = new javax.swing.JButton();
        Refresh = new javax.swing.JButton();
        Hapus = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        updateTiket = new javax.swing.JTextField();
        updateFilm = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        updateBangku = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        updatePembayaran = new javax.swing.JComboBox<>();
        kembaliLogin = new javax.swing.JButton();
        tglData = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(17, 109, 110));

        tablepembelian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nama", "no_identitas", "jumlah_tiket", "pilih_film", "pilih_bangku", "pilih_tanggal", "metode_pembayaran"
            }
        ));
        tablepembelian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablepembelianMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablepembelian);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Data Pemesanan");

        Update.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Update.setForeground(new java.awt.Color(255, 51, 0));
        Update.setText("Update");
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });

        Refresh.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Refresh.setForeground(new java.awt.Color(255, 51, 0));
        Refresh.setText("Refresh");
        Refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshActionPerformed(evt);
            }
        });

        Hapus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Hapus.setForeground(new java.awt.Color(255, 51, 0));
        Hapus.setText("Hapus");
        Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Jumlah Tiket");

        jLabel5.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Pilih Film");

        updateFilm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 Kakak 7 Ponakan", "Jumbo", "Pengantin Iblis", "Final Destination Bloodlines", "Perayaan Mati Rasa", "keluarga Super Irit", " " }));
        updateFilm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateFilmActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("pilih Bangku");

        jLabel2.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("pilih tanggal");

        jLabel3.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Metode Pembayaran");

        updatePembayaran.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Transfer", "Cash" }));

        kembaliLogin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        kembaliLogin.setForeground(new java.awt.Color(255, 51, 0));
        kembaliLogin.setText("Kembali");
        kembaliLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Update, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(111, 111, 111)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(updateBangku, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(updateTiket, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(updateFilm, javax.swing.GroupLayout.Alignment.TRAILING, 0, 318, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(updatePembayaran, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tglData, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(kembaliLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(237, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(kembaliLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(updateTiket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Update)
                        .addGap(12, 12, 12)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(updateFilm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Refresh)
                    .addComponent(updateBangku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addComponent(Hapus)
                        .addGap(40, 40, 40))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tglData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(updatePembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshActionPerformed
        // TODO add your handling code here:
        /**
     * Mengambil dan menampilkan ulang data dari database ke dalam tabel.
     *
     * @param evt event dari tombol Refresh
     */
       try (Connection konnek = koneksi.getConnection()) {
            String sql = "SELECT * FROM pembelian";
            PreparedStatement pst = konnek.prepareStatement(sql);
            ResultSet r = pst.executeQuery();
            
            javax.swing.table.DefaultTableModel modelTabel = new javax.swing.table.DefaultTableModel(
                new String[]{"Nama", "nomor_identitas", "Jumlah_Tiket", "pilih_film", "pilih_bangku", "tanggal","metode_pembayaran"}, 0
            );
     while (r.next()) {
                modelTabel.addRow(new Object[]{
                    r.getString("nama"),
                    r.getInt("nomor_identitas"),
                    r.getString("jumlah_tiket"),
                    r.getString("pilih_film"),
                    r.getString("pilih_bangku"),
                    r.getDate("tanggal"),
                    r.getString("metode_pembayaran")
                });
            }
            tablepembelian.setModel(modelTabel);

            //tablepembelian.getColumnModel().getColumn(5).setMinWidth(0);
           // tablepembelian.getColumnModel().getColumn(5).setMaxWidth(0);
           // tablepembelian.getColumnModel().getColumn(5).setWidth(0);
           // 
             } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal load data: " + e.getMessage());
        }  
    }//GEN-LAST:event_RefreshActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        // TODO add your handling code here:    
        /**
     * Mengupdate data pemesanan berdasarkan pilihan baris yang dipilih di tabel.
     *
     * @param evt event dari tombol Update
     */
        int milih = tablepembelian.getSelectedRow();
    if (milih == -1) {
        JOptionPane.showMessageDialog(this, "Pilih data yang ingin diedit dulu.");
        return;
    }
    try {
        java.util.Date tanggalData = tglData.getDate();
        String dataJumlh= updateTiket.getText();
        String filmUpdt = updateFilm.getSelectedItem().toString();
        String bangkuUpdate = updateBangku.getText();
        String pembayaranUpdate = updatePembayaran.getSelectedItem().toString();
        
        if (tanggalData == null || dataJumlh.isEmpty() || bangkuUpdate.isEmpty()) {
            JOptionPane.showMessageDialog(this, "harus diisi.");
            return;
        }
         if (!dataJumlh.matches("\\d+")) {
            JOptionPane.showMessageDialog(this, "harus angka.");
            return;
        }
         
        int jum = Integer.parseInt(dataJumlh);
        java.sql.Date sqlTanggal = new java.sql.Date(tanggalData.getTime());
        int id = (int) tablepembelian.getValueAt(milih, 1);
        
        try (Connection konek = koneksi.getConnection()) {
            String sql = "UPDATE pembelian SET tanggal=?, pilih_film=?, pilih_bangku=?,metode_pembayaran=?,jumlah_Tiket =?  WHERE nomor_identitas=?";
            PreparedStatement ps = konek.prepareStatement(sql);
            ps.setDate(1, sqlTanggal);
            ps.setString(2, filmUpdt);
            ps.setString(3, bangkuUpdate);
            ps.setString(4, pembayaranUpdate );
            ps.setInt(5,jum);
            ps.setInt(6, id);
            ps.executeUpdate();
          
            JOptionPane.showMessageDialog(this, "Data berhasil diedit.");
             RefreshActionPerformed(null);
        }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal load data: " + e.getMessage());
        
    }
    }//GEN-LAST:event_UpdateActionPerformed

    private void tablepembelianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablepembelianMouseClicked
        // TODO add your handling code here:
         /**
     * Event handler saat pengguna mengklik baris di tabel.
     * (Belum diimplementasikan untuk menampilkan detail ke form input)
     *
     * @param evt event klik mouse pada tabel
     */
        
    }//GEN-LAST:event_tablepembelianMouseClicked

    private void HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusActionPerformed
        // TODO add your handling code here:
         /**
     * Menghapus data pemesanan berdasarkan baris yang dipilih di tabel.
     *
     * @param evt event dari tombol Hapus
     */
        int milih = tablepembelian.getSelectedRow();
    if (milih == -1) {
        JOptionPane.showMessageDialog(this, "Pilih yang ingin dihapus.");
        return;
    }
    int konfirmasi = JOptionPane.showConfirmDialog(this, "Yakin ingin hapus data ini?", "Hapus Data", JOptionPane.YES_NO_OPTION);
    if (konfirmasi == JOptionPane.YES_OPTION) {
        try {
            int id = (int) tablepembelian.getValueAt(milih, 1); // ID di kolom tersembunyi

            try (Connection konek = koneksi.getConnection()) {
                String sql = "DELETE FROM pembelian WHERE nomor_identitas=?";
                PreparedStatement ps = konek.prepareStatement(sql);
                ps.setInt(1, id);
                ps.executeUpdate();

                JOptionPane.showMessageDialog(this, "Data berhasil dihapus.");
                RefreshActionPerformed(null);
            }
             } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal hapus data: " + e.getMessage());
        }
    }
        
    }//GEN-LAST:event_HapusActionPerformed

    private void updateFilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateFilmActionPerformed
        // TODO add your handling code here:
        /**
     * Event handler untuk perubahan pilihan combo box film.
     *
     * @param evt event dari combo box
     */
    }//GEN-LAST:event_updateFilmActionPerformed

    private void kembaliLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliLoginActionPerformed
        // TODO add your handling code here:
        /**
     * Kembali ke tampilan login dari AdminFrame.
     *
     * @param evt event dari tombol Kembali
     */
         this.dispose();
         new LoginFrame().setVisible(true);
    }//GEN-LAST:event_kembaliLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /**
     * Method utama untuk menjalankan tampilan AdminFrame.
     *
     * @param args argumen baris perintah (tidak digunakan)
     */
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Hapus;
    private javax.swing.JButton Refresh;
    private javax.swing.JButton Update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton kembaliLogin;
    private javax.swing.JTable tablepembelian;
    private com.toedter.calendar.JDateChooser tglData;
    private javax.swing.JTextField updateBangku;
    private javax.swing.JComboBox<String> updateFilm;
    private javax.swing.JComboBox<String> updatePembayaran;
    private javax.swing.JTextField updateTiket;
    // End of variables declaration//GEN-END:variables
}
