/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CINETIX;

import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author Arta
 */

interface Harga {
    int HARGA_TIKET = 50000;

    default int hitungHarga(int jumlah) {
        return jumlah * HARGA_TIKET;
    }

    String formatStruk();
}
class User {
    protected String nama;
    protected String identitas;

    public User(String nama, String identitas) {
        this.nama = nama;
        this.identitas = identitas;
    }
     public String getNama() {
        return nama;
    }

    public void setNama(String nama) {
        this.nama = nama;
    }

    public String getIdentitas() {
        return identitas;
    }

    public void setIdentitas(String identitas) {
        this.identitas = identitas;
}
}
class Tiket extends User implements Harga {
    private int jumlah;

    public Tiket(String nama, String identitas, int jumlah) {
        super(nama, identitas); // super constructor (7)
        this.jumlah = jumlah;
    }
     @Override
    public String formatStruk() {
        return "Nama: " + nama + "\nIdentitas: " + identitas + "\nJumlah: " + jumlah + "\nTotal: Rp " + hitungHarga(jumlah);
    }

    // Overloading (6)
    public String formatStruk(String metode) {
        return formatStruk() + "\nMetode: " + metode;
    }
}

public class BeliTiket extends javax.swing.JFrame {

    /**
     * Creates new form BeliTiket
     */
    public BeliTiket() {
        initComponents();
        this.setSize(680, 440); // Ukuran disesuaikan dengan SS
    this.setLocationRelativeTo(null);
    this.setResizable(false); 
    }

        // (GUI komponen tetap, tidak ditampilkan ulang di sini)

        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        buttonKembali = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        cbFilm = new javax.swing.JComboBox<>();
        namaPembeli = new javax.swing.JTextField();
        buttonBangku = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        tanggal = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        cbPembayaran = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jumlahTiket = new javax.swing.JTextField();
        nomorIdentitas = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        buttonOk = new javax.swing.JButton();
        pilihBangku = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 51, 0));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 0));
        jLabel1.setText("Pengisian Data Diri :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 150, 16);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 0));
        jLabel2.setText("Nama");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 60, 37, 16);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 0));
        jLabel3.setText("Nomor Identitas");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 100, 110, 16);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 51, 0));
        jLabel4.setText("Jumlah Tiket");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 140, 110, 16);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 51, 0));
        jLabel5.setText("Pilih Film");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 180, 110, 16);

        buttonKembali.setBackground(new java.awt.Color(255, 51, 0));
        buttonKembali.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonKembali.setText("Kembali");
        buttonKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKembaliActionPerformed(evt);
            }
        });
        getContentPane().add(buttonKembali);
        buttonKembali.setBounds(10, 370, 100, 23);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 51, 0));
        jLabel6.setText("Pilih Bangku");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 220, 120, 16);

        cbFilm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 Kakak 7 Ponakan", "Jumbo", "Pengantin Iblis", "Final Destination Bloodlines", "Perayaan Mati Rasa", "keluarga Super Irit" }));
        cbFilm.setPreferredSize(new java.awt.Dimension(64, 22));
        cbFilm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFilmActionPerformed(evt);
            }
        });
        getContentPane().add(cbFilm);
        cbFilm.setBounds(200, 180, 230, 22);
        getContentPane().add(namaPembeli);
        namaPembeli.setBounds(200, 60, 230, 22);

        buttonBangku.setBackground(new java.awt.Color(255, 51, 0));
        buttonBangku.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonBangku.setText("Deskripsi bangku");
        buttonBangku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBangkuActionPerformed(evt);
            }
        });
        getContentPane().add(buttonBangku);
        buttonBangku.setBounds(400, 360, 150, 30);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 51, 0));
        jLabel7.setText("Pilih Tanggal");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 260, 80, 16);

        tanggal.setPreferredSize(new java.awt.Dimension(64, 22));
        getContentPane().add(tanggal);
        tanggal.setBounds(200, 260, 230, 22);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 51, 0));
        jLabel8.setText("Metode Pembayaran");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 300, 150, 16);

        cbPembayaran.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Transfer", "Cash" }));
        cbPembayaran.setPreferredSize(new java.awt.Dimension(64, 22));
        getContentPane().add(cbPembayaran);
        cbPembayaran.setBounds(200, 300, 230, 22);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jumlahTiket, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 230, -1));
        jPanel1.add(nomorIdentitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 230, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, 200, 270));

        buttonOk.setBackground(new java.awt.Color(255, 51, 0));
        buttonOk.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonOk.setText("OKE");
        buttonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOkActionPerformed(evt);
            }
        });
        jPanel1.add(buttonOk, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 360, 100, 30));

        pilihBangku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihBangkuActionPerformed(evt);
            }
        });
        jPanel1.add(pilihBangku, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 230, -1));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 680, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbFilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFilmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbFilmActionPerformed

    private void buttonKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKembaliActionPerformed
        // TODO add your handling code here:
         this.dispose();
          
         new TampilanAwal().setVisible(true);
    }//GEN-LAST:event_buttonKembaliActionPerformed

    private void buttonBangkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBangkuActionPerformed
        // TODO add your handling code here:
         this.dispose();
         new DeskripsiBangku().setVisible(true);
    }//GEN-LAST:event_buttonBangkuActionPerformed

    private void buttonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOkActionPerformed
        // TODO add your handling code here:
        
    String nama = namaPembeli.getText();
    String identitas = nomorIdentitas.getText();
    String jumlahStr = jumlahTiket.getText();
    String film = cbFilm.getSelectedItem().toString();
    String bangku = pilihBangku.getText().toString();
    String metode = cbPembayaran.getSelectedItem().toString();
    java.util.Date tanggalDate = tanggal.getDate();
    java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd");
    String tanggalStr = sdf.format(tanggalDate);


    int jumlah;
    try {
        jumlah = Integer.parseInt(jumlahStr);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Jumlah tiket tidak valid!", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Konfirmasi
    int konfirmasi = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin membeli tiket?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
    if (konfirmasi == JOptionPane.NO_OPTION) {
        return; // tidak jadi beli
    }

    Tiket tiket = new Tiket(nama, identitas, jumlah);
    int totalHarga = tiket.hitungHarga(jumlah);

    // Simpan ke database
    try (Connection conn = koneksi.getConnection()) {
        String sql = "INSERT INTO pembelian (nama, nomor_identitas, Jumlah_Tiket, Pilih_film, Pilih_bangku, tanggal, metode_pembayaran) VALUES (?, ?, ?, ?, ?, ?, ?)";
        PreparedStatement ps = conn.prepareStatement(sql);
        ps.setString(1, nama);
        ps.setString(2, identitas);
        ps.setInt(3, jumlah);
        ps.setString(4, film);
        ps.setString(5, bangku);
        ps.setString(6, tanggalStr);
        ps.setString(7, metode);
        
        ps.executeUpdate();

        // Tampilkan struk
        String isiStruk = "===== TIKET ANDA =====\n"
                + "Nama: " + nama + "\n"
                + "Identitas: " + identitas + "\n"
                + "Jumlah: " + jumlah + "\n"
                + "Metode: " + metode + "\n"
                + "Film: " + film + "\n"
                + "Bangku: " + bangku + "\n"
                + "Tanggal: " + tanggalStr + "\n"
                + "--------------------------\n"
                + "Total: Rp " + totalHarga + "\n"
                + "Terima Kasih telah memesan Tiket" + "\n"
                +"selamat Menonton";
                

        jTextArea1.setText(isiStruk);
        JOptionPane.showMessageDialog(this, "Tiket berhasil dibeli dan disimpan ke database!");

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal menyimpan ke database:\n" + e.getMessage());
    }


    }//GEN-LAST:event_buttonOkActionPerformed

    private void pilihBangkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihBangkuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pilihBangkuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BeliTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BeliTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BeliTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BeliTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BeliTiket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonBangku;
    private javax.swing.JButton buttonKembali;
    private javax.swing.JButton buttonOk;
    private javax.swing.JComboBox<String> cbFilm;
    private javax.swing.JComboBox<String> cbPembayaran;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jumlahTiket;
    private javax.swing.JTextField namaPembeli;
    private javax.swing.JTextField nomorIdentitas;
    private javax.swing.JTextField pilihBangku;
    private com.toedter.calendar.JDateChooser tanggal;
    // End of variables declaration//GEN-END:variables
}
