/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CINETIX;

/**
 *
 * @author Arta
 */
public class DaftarFilm extends javax.swing.JFrame {

    /**
     * Creates new form DaftarFilm
     */
    public DaftarFilm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 0));
        jLabel1.setText("Film yang Sedang Tayang");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(298, 0, 230, 25);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(245, 64, 0, 0);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CINETIX/Film 1 Kakak 7 Ponakan.jpg"))); // NOI18N
        jLabel3.setMaximumSize(new java.awt.Dimension(150, 170));
        jLabel3.setMinimumSize(new java.awt.Dimension(100, 150));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 70, 185, 251);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CINETIX/Film Jumbo.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(300, 71, 248, 250);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CINETIX/Film Horor.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(560, 70, 179, 251);

        jLabel6.setToolTipText("");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(229, 245, 0, 0);
        getContentPane().add(jLabel7);
        jLabel7.setBounds(38, 855, 0, 0);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CINETIX/Final Destination bloodlines.jpg"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(40, 390, 185, 247);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CINETIX/Mati Rasa.jpg"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(300, 390, 183, 251);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CINETIX/Keluarga Super Irit.jpg"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(550, 390, 202, 250);

        jLabel11.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 51, 51));
        jLabel11.setText("1 Kakak 7 Ponakan");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(70, 330, 130, 16);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(251, 51, 0));
        jLabel12.setText("Jumbo");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(360, 330, 70, 16);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(251, 51, 0));
        jLabel13.setText("Pengantin Iblis");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(600, 320, 130, 16);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(251, 51, 0));
        jLabel14.setText("Final Destination Bloodlines");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(40, 680, 180, 20);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(251, 51, 0));
        jLabel15.setText("Perayaan Mati Rasa");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(330, 660, 170, 16);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(251, 51, 0));
        jLabel16.setText("Keluarga Super Irit");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(570, 660, 140, 20);

        jButton1.setBackground(new java.awt.Color(251, 51, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Kembali");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 740, 115, 58);
        getContentPane().add(jLabel17);
        jLabel17.setBounds(0, 0, 0, 0);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
         new TampilanAwal().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DaftarFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DaftarFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DaftarFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DaftarFilm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DaftarFilm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
