/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CINETIX;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.awt.Cursor;
import javax.swing.JOptionPane;
/**
 *
 * @author Arta
 */
public class LoginFrame extends javax.swing.JFrame {

    private static class Admin {

        public Admin() {
        }

        private void setVisible(boolean b) {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }
    }
    public interface UserAction {
        /**
     * Melakukan proses login berdasarkan data pengguna.
     * Harus diimplementasikan oleh class yang mengimplementasi interface ini.
     */
    void login(); // abstract
    /**
     * Menampilkan pesan sambutan standar untuk pengguna.
     * Dapat dipanggil langsung tanpa membuat objek.
     */
    static void welcomeMessage() {
        System.out.println("Selamat datang di aplikasi!");
        /**
     * Menampilkan peran (role) dari pengguna.
     * Bisa digunakan langsung oleh class yang mengimplementasi.
     */
    }

    default void showRole(String role) {
        System.out.println("Login sebagai: " + role);
    }
}
    public class LoginProcessor implements UserAction {
    private String username;
    private String password;
    private String role;
    /**
     * Constructor untuk menginisialisasi data login.
     */

    public LoginProcessor(String username, String password, String role) {
        this.username = username;
        this.password = password;
        this.role = role;
    }
     /**
     * Mengecek apakah data login sesuai dengan akun yang tersedia.
     * Menampilkan hasil login ke console.
     */
    @Override
    public void login() {
        if (username.equals("admin") && password.equals("admin123") && role.equals("Admin")) {
            System.out.println("Login berhasil sebagai Admin.");
        } else if (username.equals("user") && password.equals("user123") && role.equals("User")) {
            System.out.println("Login berhasil sebagai User.");
        } else {
            System.out.println("Login gagal.");
        }
    }
}
    public class Person {
    protected String name;
    
    /**
     * Constructor untuk membuat objek Person.
     */

    public Person(String name) {
        this.name = name;
    }
    /**
     * Menampilkan informasi nama ke console.
     */
    public void displayInfo() {
        System.out.println("Nama: " + name);
    }
}

public class User extends Person {
    private String role;
    /**
     * Constructor untuk membuat objek User dengan nama dan peran.
     */

    public User(String name, String role) {
        super(name);
        this.role = role;
    }
    /**
     * Menampilkan informasi user termasuk nama dan peran.
     */
    public void displayUser() {
        super.displayInfo();
        System.out.println("Sebagai: " + role);
    }
}

    /**
     * Creates new form LoginFrame
     */
    public LoginFrame() {
        initComponents();
        setSize(650, 500);
       setLocationRelativeTo(null); // Menempatkan frame di tengah layar
         setVisible(true); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Isinama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Isipass = new javax.swing.JPasswordField();
        tampilPassword1 = new javax.swing.JCheckBox();
        Login = new javax.swing.JButton();
        BalikKeRegis = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        role = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(251, 51, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CINETIX/LogoCineTix2.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(570, 10, 84, 60);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(251, 51, 0));
        jLabel2.setText("Masukkan Username Anda");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(70, 80, 177, 20);
        jPanel1.add(Isinama);
        Isinama.setBounds(73, 108, 390, 22);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(251, 51, 0));
        jLabel3.setText("Masukkan Password Anda");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(70, 150, 174, 20);

        Isipass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IsipassActionPerformed(evt);
            }
        });
        jPanel1.add(Isipass);
        Isipass.setBounds(73, 174, 390, 22);

        tampilPassword1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tampilPassword1.setForeground(new java.awt.Color(251, 51, 0));
        tampilPassword1.setText("Perlihatkan Password");
        tampilPassword1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tampilPassword11ActionPerformed(evt);
            }
        });
        jPanel1.add(tampilPassword1);
        tampilPassword1.setBounds(73, 202, 150, 20);

        Login.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Login.setForeground(new java.awt.Color(251, 51, 0));
        Login.setText("Masuk");
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });
        jPanel1.add(Login);
        Login.setBounds(70, 290, 390, 40);

        BalikKeRegis.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BalikKeRegis.setForeground(new java.awt.Color(251, 51, 0));
        BalikKeRegis.setText("Buat Akun Yukk, Klik disini");
        BalikKeRegis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BalikKeRegisMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BalikKeRegisMouseEntered(evt);
            }
        });
        jPanel1.add(BalikKeRegis);
        BalikKeRegis.setBounds(170, 360, 170, 10);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(251, 51, 0));
        jLabel5.setText("Masuk!");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(270, 20, 70, 30);

        role.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "masuk sebagai", "admin", "user" }));
        jPanel1.add(role);
        role.setBounds(70, 240, 150, 22);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 661, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
        // TODO add your handling code here:
        String username = Isinama.getText();
    String password = new String(Isipass.getPassword());
    
     if (username.isEmpty() || password.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Username dan Password tidak boleh kosong!");
        return;
    } else

    if (password.length() >= 10) {
        JOptionPane.showMessageDialog(this, "Password maksimal 10 karakter.");
        return;
    }
      if (username.equals("admin") && password.equals("admin123") && role.equals("admin")) {
        JOptionPane.showMessageDialog(this, "Login berhasil sebagai Admin");

        Admin admin = new Admin(); // Ganti dengan nama frame admin kamu
        admin.setVisible(true);
        this.dispose();
        new Admin().setVisible(true);
        return;
    }
      if (role.equals("user")) {
     
     
     try (Connection conn = koneksi.getConnection()) {
        String sql = "SELECT * FROM user WHERE username=? AND password=?";
        PreparedStatement stmt = conn.prepareStatement(sql);
        stmt.setString(1, username);
        stmt.setString(2, password);
        
        ResultSet rs = stmt.executeQuery();
        if (rs.next()) {
            JOptionPane.showMessageDialog(this, "Login Berhasil!");
            JOptionPane.showMessageDialog(this,"Selamat Datang " + username);
            new TampilanAwal().setVisible(true);
            } else {
            JOptionPane.showMessageDialog(this, "Username atau password salah!", "Login Gagal", JOptionPane.ERROR_MESSAGE);
        }
         } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Terjadi Kesalahan Database", "Error", JOptionPane.ERROR_MESSAGE);
    }        
      }
    }//GEN-LAST:event_LoginActionPerformed

    private void BalikKeRegisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BalikKeRegisMouseClicked
        // TODO add your handling code here:
             this.dispose();
         new RegistFrame().setVisible(true);
    }//GEN-LAST:event_BalikKeRegisMouseClicked

    private void BalikKeRegisMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BalikKeRegisMouseEntered
        // TODO add your handling code here:
         BalikKeRegis.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_BalikKeRegisMouseEntered

    private void tampilPassword11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tampilPassword11ActionPerformed
        // TODO add your handling code here:
        if (tampilPassword1.isSelected()) {
            Isipass.setEchoChar((char) 0);
        } else {
            Isipass.setEchoChar('*');

        }
    }//GEN-LAST:event_tampilPassword11ActionPerformed

    private void IsipassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IsipassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IsipassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BalikKeRegis;
    private javax.swing.JTextField Isinama;
    private javax.swing.JPasswordField Isipass;
    private javax.swing.JButton Login;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> role;
    private javax.swing.JCheckBox tampilPassword1;
    // End of variables declaration//GEN-END:variables
}
