/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CINETIX;

import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author Arta
 * @author Daffa
 */
/**
 * Interface untuk mencetak struk tiket bioskop.
 */
interface CetakStruk {
    /**
     * Mencetak isi struk pembelian tiket.
     *
     * @return String yang berisi ucapan terima kasih dan info menonton.
     */
    String cetak();
    /**
     * Memberikan informasi default struk.
     *
     * @return String informasi default struk.
     */

    default String infoDefault() {
        return "Struk dicetak otomatis";
    }

    static String printHeader() {
        return "===== STRUK PEMBELIAN =====";
    }
}
/**
 * Kelas abstrak yang merepresentasikan pembelian tiket dasar.
 */
class Pembelian {
    protected String nama;
    protected String identitas;
    protected int jumlah;
     /**
     * Konstruktor untuk membuat objek pembelian berdasarkan nama dan identitas.
     *
     * @param nama Nama pembeli.
     * @param identitas Nomor identitas pembeli.
     */
    public Pembelian(String nama, String identitas) {
        this.nama = nama;
    this.identitas = identitas;
    /**
     * Konstruktor untuk inisialisasi jumlah tiket saja.
     *
     * @param jumlah Jumlah tiket yang dibeli.
     */
    }
    public Pembelian(int jumlah){
        this.jumlah = jumlah;
    }
    /**
     * Menghitung harga total berdasarkan jumlah tiket.
     *
     * @param jumlah Jumlah tiket.
     * @return Total harga.
     */
    public int hitungHarga(int jumlah) {
        return jumlah * 50000;
    }
    public void setNama(String nama) {
        this.nama = nama;
    }

    public void setIdentitas(String identitas) {
        this.identitas = identitas;
    }

   

    public String getNama() { return nama; }
    public String getIdentitas() { return identitas; }
    public int getJumlah() { return jumlah; }
}
/**
 * Kelas yang merepresentasikan tiket bioskop, turunan dari Pembelian
 * dan mengimplementasikan CetakStruk.
 */
class Tiket extends Pembelian implements CetakStruk {
    /**
     * Konstruktor untuk membuat objek Tiket.
     *
     * @param nama Nama pembeli.
     * @param identitas Nomor identitas pembeli.
     * @param jumlah Jumlah tiket yang dibeli.
     */

    public Tiket(String nama, String identitas, int jumlah) {
        super(nama, identitas);
        this.jumlah = jumlah;
    }
    /**
     * Menghitung total harga tiket.
     *
     * @param jumlah Jumlah tiket.
     * @return Total harga.
     */

    @Override
    public int hitungHarga(int jumlah) {
        return super.hitungHarga(jumlah);
    }
    /**
     * Menampilkan pesan ucapan setelah pembelian tiket.
     *
     * @return Pesan ucapan.
     */
    @Override
    public String cetak() {
        return "Terima Kasih telah memesan Tiket\nSelamat Menonton";
    }
}
    public class BeliTiket extends javax.swing.JFrame {
        /**
     * Konstruktor utama yang menginisialisasi komponen GUI.
     */
    public BeliTiket() {
        initComponents();
        this.setSize(680, 440); // Ukuran disesuaikan dengan SS
        this.setLocationRelativeTo(null);
        this.setResizable(false); 
}
     /**
     * Event handler ketika tombol "Kembali" ditekan.
     *
     * @param evt Event tombol klik.
     */
        // (GUI komponen tetap, tidak ditampilkan ulang di sini)

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        buttonKembali = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        cbFilm = new javax.swing.JComboBox<>();
        namaPembeli = new javax.swing.JTextField();
        buttonBangku = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbPembayaran = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jumlahTiket = new javax.swing.JTextField();
        nomorIdentitas = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextArea = new javax.swing.JTextArea();
        buttonOk = new javax.swing.JButton();
        pilihBangku = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tanggal = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 51, 0));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI Variable", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nama");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 60, 37, 16);

        jLabel3.setFont(new java.awt.Font("Segoe UI Variable", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nomor Identitas");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 100, 110, 16);

        jLabel4.setFont(new java.awt.Font("Segoe UI Variable", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Jumlah Tiket");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 140, 110, 16);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Pilih Film");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 180, 110, 16);

        buttonKembali.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonKembali.setForeground(new java.awt.Color(255, 51, 0));
        buttonKembali.setText("Kembali");
        buttonKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonKembaliActionPerformed(evt);
            }
        });
        getContentPane().add(buttonKembali);
        buttonKembali.setBounds(10, 370, 100, 23);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Pilih Bangku");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 220, 120, 16);

        cbFilm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 Kakak 7 Ponakan", "Jumbo", "Pengantin Iblis", "Final Destination Bloodlines", "Perayaan Mati Rasa", "keluarga Super Irit" }));
        cbFilm.setPreferredSize(new java.awt.Dimension(64, 22));
        cbFilm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFilmActionPerformed(evt);
            }
        });
        getContentPane().add(cbFilm);
        cbFilm.setBounds(200, 180, 230, 22);
        getContentPane().add(namaPembeli);
        namaPembeli.setBounds(200, 60, 230, 30);

        buttonBangku.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonBangku.setForeground(new java.awt.Color(255, 51, 0));
        buttonBangku.setText("Deskripsi bangku");
        buttonBangku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBangkuActionPerformed(evt);
            }
        });
        getContentPane().add(buttonBangku);
        buttonBangku.setBounds(400, 360, 150, 30);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Pilih Tanggal");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 260, 80, 16);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Metode Pembayaran");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 300, 150, 16);

        cbPembayaran.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Transfer", "Cash" }));
        cbPembayaran.setPreferredSize(new java.awt.Dimension(64, 22));
        getContentPane().add(cbPembayaran);
        cbPembayaran.setBounds(200, 300, 230, 22);

        jPanel1.setBackground(new java.awt.Color(17, 109, 110));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jumlahTiket, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 230, -1));
        jPanel1.add(nomorIdentitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 230, -1));

        TextArea.setColumns(20);
        TextArea.setRows(5);
        jScrollPane1.setViewportView(TextArea);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, 200, 270));

        buttonOk.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonOk.setForeground(new java.awt.Color(255, 51, 0));
        buttonOk.setText("OKE");
        buttonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonOkActionPerformed(evt);
            }
        });
        jPanel1.add(buttonOk, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 360, 100, 30));

        pilihBangku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihBangkuActionPerformed(evt);
            }
        });
        jPanel1.add(pilihBangku, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 230, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Pengisian Pembelian Tiket :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 240, -1));
        jPanel1.add(tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 230, -1));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 680, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbFilmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFilmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbFilmActionPerformed

    private void buttonKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonKembaliActionPerformed
        // TODO add your handling code here:
        /**
     * Event handler untuk membuka form deskripsi bangku.
     *
     * @param evt Event tombol klik.
     */
         this.dispose();
          
         new TampilanAwal().setVisible(true);
    }//GEN-LAST:event_buttonKembaliActionPerformed

    private void buttonBangkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBangkuActionPerformed
        // TODO add your handling code here:
         /**
     * Event handler ketika tombol "OKE" ditekan.
     * Akan mengambil data inputan, simpan ke database, lalu cetak struk.
     *
     * @param evt Event tombol klik.
     */
         this.dispose();
         new DeskripsiBangku().setVisible(true);
    }//GEN-LAST:event_buttonBangkuActionPerformed

    private void buttonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOkActionPerformed
        // TODO add your handling code here:
        
   
    String nama = namaPembeli.getText();
    String identitas = nomorIdentitas.getText();
    String jumlahStr = jumlahTiket.getText();
    String film = cbFilm.getSelectedItem().toString();
    String bangku = pilihBangku.getText();
    String metode = cbPembayaran.getSelectedItem().toString();
    java.util.Date tanggalDate = tanggal.getDate();
    java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("yyyy-MM-dd");
    String tanggalStr = sdf.format(tanggalDate);

    int jumlah;
    try {
        jumlah = Integer.parseInt(jumlahStr);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Jumlah tiket tidak valid!", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    int konfirmasi = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin membeli tiket?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
    if (konfirmasi == JOptionPane.NO_OPTION) return;

    Pembelian pembelian = new Tiket(nama, identitas, jumlah);
    int totalHarga = pembelian.hitungHarga(jumlah);
    
    String[] bangkuList = bangku.split(",");// ini dibuat array kalo pesen lebih dari 1
    for (int i = 0; i < bangkuList.length; i++) {
    bangkuList[i] = bangkuList[i].trim();//ini kalo masukkan ada spasi maka code ini akan menghapus spasi
}

    try (Connection conn = koneksi.getConnection()) {
        for (String b : bangkuList) {// dan ini di cek ke database nya
    String cekSql = "SELECT COUNT(*) FROM pembelian WHERE Pilih_film = ? AND Pilih_bangku LIKE ? AND tanggal = ?";
    PreparedStatement cekPs = conn.prepareStatement(cekSql);
    cekPs.setString(1, film);
    cekPs.setString(2, "%" + b + "%");
    cekPs.setString(3, tanggalStr);

    ResultSet rs = cekPs.executeQuery();
    rs.next();
    int count = rs.getInt(1);

    if (count > 0) {
        JOptionPane.showMessageDialog(this, "Bangku " + b + " sudah dipesan!", "Bangku Tidak Tersedia", JOptionPane.ERROR_MESSAGE);
        return;
    }


    }
        String sql = "INSERT INTO pembelian (nama, nomor_identitas, Jumlah_Tiket, Pilih_film, Pilih_bangku, tanggal, metode_pembayaran) VALUES (?, ?, ?, ?, ?, ?, ?)";
        PreparedStatement ps = conn.prepareStatement(sql);
        ps.setString(1, nama);
        ps.setString(2, identitas);
        ps.setInt(3, jumlah);
        ps.setString(4, film);
        ps.setString(5, bangku);
        ps.setString(6, tanggalStr);
        ps.setString(7, metode);
        ps.executeUpdate();

        // instanceof dan casting dilakukan di sini
        String strukTambahan = "";
        String infoTambahan = "";

        if (pembelian instanceof CetakStruk) {
            CetakStruk tampilStruk = (CetakStruk) pembelian;
            strukTambahan = tampilStruk.cetak();
            infoTambahan = tampilStruk.infoDefault();
        }
        
    String isiStruk = CetakStruk.printHeader() + "\n"
    + "Nama: " + nama + "\n"
    + "Identitas: " + identitas + "\n"
    + "Jumlah: " + jumlah + "\n"
    + "Metode: " + metode + "\n"
    + "Film: " + film + "\n"
    + "Bangku: " + bangku + "\n"
    + "Tanggal: " + tanggalStr + "\n"
    + "-----------------------------\n"
    + "Total: Rp " + totalHarga + "\n"
    + infoTambahan + "\n"
    + strukTambahan;


        TextArea.setText(isiStruk);
        JOptionPane.showMessageDialog(this, "Tiket berhasil dibeli dan disimpan ke database!");

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal menyimpan ke database:\n" + e.getMessage());
    }



    }//GEN-LAST:event_buttonOkActionPerformed

    private void pilihBangkuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihBangkuActionPerformed
        // TODO add your handling code here:
        /**
     * Event handler untuk pemilihan bangku (kosong karena tidak ada aksi khusus).
     *
     * @param evt Event inputan.
     */
    }//GEN-LAST:event_pilihBangkuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /**
     * Fungsi utama untuk menampilkan form.
     *
     * @param args Argumen dari command-line.
     */
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BeliTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BeliTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BeliTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BeliTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BeliTiket().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea TextArea;
    private javax.swing.JButton buttonBangku;
    private javax.swing.JButton buttonKembali;
    private javax.swing.JButton buttonOk;
    private javax.swing.JComboBox<String> cbFilm;
    private javax.swing.JComboBox<String> cbPembayaran;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jumlahTiket;
    private javax.swing.JTextField namaPembeli;
    private javax.swing.JTextField nomorIdentitas;
    private javax.swing.JTextField pilihBangku;
    private com.toedter.calendar.JDateChooser tanggal;
    // End of variables declaration//GEN-END:variables
}
