/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CINETIX;

import java.awt.Cursor;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author Arta
 * @author Daffa
 */
public class RegistFrame extends javax.swing.JFrame {
    /**
     * Konstruktor default untuk RegistFrame.
     * Menyusun komponen GUI dan menampilkan frame di tengah layar.
     */

    /**
     * Creates new form RegistFrame
     */
    public RegistFrame() {
        initComponents();
    setSize(650, 500);
    setLocationRelativeTo(null); // Menempatkan frame di tengah layar
    setVisible(true); 
    }
 /**
     * Listener untuk tombol registrasi akun.
     * Memvalidasi input dan menyimpan data user ke database jika valid.
     * Jika berhasil, berpindah ke LoginFrame.
     *
     * @param evt Event saat tombol ditekan
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        Login = new javax.swing.JButton();
        BalikKeRegis = new javax.swing.JLabel();
        role = new javax.swing.JComboBox<>();
        tampilPassword1 = new javax.swing.JCheckBox();
        Isipass = new javax.swing.JPasswordField();
        Isinama = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        registNama = new javax.swing.JLabel();
        inputNama = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        inputPassword = new javax.swing.JPasswordField();
        tampilPassword = new javax.swing.JCheckBox();
        labelPassword = new javax.swing.JLabel();
        tombolOke = new javax.swing.JButton();
        labelAkun = new javax.swing.JLabel();

        jPanel2.setBackground(new java.awt.Color(50, 30, 30));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(51, 51, 51), new java.awt.Color(51, 51, 51), new java.awt.Color(51, 51, 51), new java.awt.Color(51, 51, 51)));

        Login.setBackground(new java.awt.Color(17, 109, 110));
        Login.setFont(new java.awt.Font("Segoe UI Variable", 1, 12)); // NOI18N
        Login.setForeground(new java.awt.Color(251, 51, 0));
        Login.setText("Masuk");
        Login.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });

        BalikKeRegis.setFont(new java.awt.Font("Segoe UI Variable", 1, 12)); // NOI18N
        BalikKeRegis.setForeground(new java.awt.Color(251, 51, 0));
        BalikKeRegis.setText("Buat Akun");
        BalikKeRegis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BalikKeRegisMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BalikKeRegisMouseEntered(evt);
            }
        });

        role.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "masuk sebagai", "admin", "user" }));

        tampilPassword1.setBackground(new java.awt.Color(50, 30, 30));
        tampilPassword1.setFont(new java.awt.Font("Segoe UI Variable", 1, 12)); // NOI18N
        tampilPassword1.setForeground(new java.awt.Color(251, 51, 0));
        tampilPassword1.setText("Perlihatkan Password");
        tampilPassword1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tampilPassword11ActionPerformed(evt);
            }
        });

        Isipass.setToolTipText("Password");
        Isipass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IsipassActionPerformed(evt);
            }
        });

        Isinama.setToolTipText("Username");
        Isinama.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Isinama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IsinamaActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI Variable", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(205, 24, 24));
        jLabel5.setText("LOGIN");

        jLabel2.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(251, 51, 0));
        jLabel2.setText("Username");

        jLabel4.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(251, 51, 0));
        jLabel4.setText("Password");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(tampilPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                            .addComponent(BalikKeRegis))
                        .addComponent(Isipass)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Isinama))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(Login, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(role, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Isinama, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Isipass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tampilPassword1)
                    .addComponent(BalikKeRegis, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(role, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(Login, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(17, 109, 110));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, -1, -1));

        jPanel3.setBackground(new java.awt.Color(50, 30, 30));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title.setBackground(new java.awt.Color(255, 255, 255));
        Title.setFont(new java.awt.Font("Segoe UI Variable", 1, 24)); // NOI18N
        Title.setForeground(new java.awt.Color(255, 51, 0));
        Title.setText("Buat Akun");
        jPanel3.add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        registNama.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        registNama.setForeground(new java.awt.Color(255, 51, 0));
        registNama.setText("Buat Username Anda");
        jPanel3.add(registNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 210, 20));

        inputNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNamaActionPerformed(evt);
            }
        });
        jPanel3.add(inputNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 260, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI Variable", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 0));
        jLabel3.setText("Buat Password Anda");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 260, 20));

        inputPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPasswordActionPerformed(evt);
            }
        });
        jPanel3.add(inputPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 260, 30));

        tampilPassword.setBackground(new java.awt.Color(0, 0, 0));
        tampilPassword.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tampilPassword.setForeground(new java.awt.Color(17, 109, 110));
        tampilPassword.setText("Perlihatkan Password");
        tampilPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tampilPasswordActionPerformed(evt);
            }
        });
        jPanel3.add(tampilPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 160, 10));

        labelPassword.setBackground(new java.awt.Color(255, 255, 255));
        labelPassword.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        labelPassword.setForeground(new java.awt.Color(17, 109, 110));
        labelPassword.setText("  Maksimal 10 karakter");
        jPanel3.add(labelPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 220, 20));

        tombolOke.setBackground(new java.awt.Color(17, 109, 110));
        tombolOke.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        tombolOke.setForeground(new java.awt.Color(255, 255, 255));
        tombolOke.setText("Buat Akun");
        tombolOke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolOkeActionPerformed(evt);
            }
        });
        jPanel3.add(tombolOke, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 270, 30));

        labelAkun.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelAkun.setForeground(new java.awt.Color(17, 109, 110));
        labelAkun.setText("Sudah Punya Akun? Login");
        labelAkun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelAkunMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelAkunMouseEntered(evt);
            }
        });
        jPanel3.add(labelAkun, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 170, 20));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 370, 330));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 640, 480);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNamaActionPerformed

    private void tombolOkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolOkeActionPerformed
             // TODO add your handling code here:
    /**
     * Listener untuk tombol login.
     * Memvalidasi input login dan mencocokkan data ke database.
     * Login admin menggunakan username/password tetap.
     * Jika berhasil login, membuka frame sesuai role.
     *
     * @param evt Event saat tombol ditekan
     */         
    String username = inputNama.getText();
    String password = new String(inputPassword.getPassword());
    
     if (username.isEmpty() || password.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Username dan Password tidak boleh kosong!");
        return;
    } else

    if (password.length() >= 10) {
        JOptionPane.showMessageDialog(this, "Password maksimal 10 karakter.");
        return;
    } 
      try (Connection conn = koneksi.getConnection()) {
        String check = "SELECT * FROM user WHERE username=?";
        PreparedStatement psCheck = conn.prepareStatement(check);
        psCheck.setString(1, username);


        ResultSet rs = psCheck.executeQuery();
        if (rs.next()) {
            JOptionPane.showMessageDialog(this, "Username sudah digunakan!");
            return;
        }
         String sql = "INSERT INTO user (username, password) VALUES (?, ?)";
        PreparedStatement ps = conn.prepareStatement(sql);
        ps.setString(1, username);
        ps.setString(2, password);
        ps.executeUpdate();

        JOptionPane.showMessageDialog(this, "Register berhasil!");
        this.dispose(); new LoginFrame().setVisible(true);
    } catch (Exception e) {
        e.printStackTrace(); 
        JOptionPane.showMessageDialog(this, "Terjadi error saat register: " + e.getMessage());
    }

    }//GEN-LAST:event_tombolOkeActionPerformed

    private void inputPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputPasswordActionPerformed

    private void tampilPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tampilPasswordActionPerformed
        // TODO add your handling code here:
         if (tampilPassword.isSelected()) {
        inputPassword.setEchoChar((char) 0); 
    } else {
        inputPassword.setEchoChar('*'); 
        
    }
    }//GEN-LAST:event_tampilPasswordActionPerformed

    private void labelAkunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelAkunMouseClicked
        // TODO add your handling code here:
        /**
     * Mengubah kursor menjadi tangan saat mouse hover di label "Login".
     *
     * @param evt Event mouse masuk
     */
       this.dispose();
       new LoginFrame().setVisible(true);
        
    }//GEN-LAST:event_labelAkunMouseClicked

    private void labelAkunMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelAkunMouseEntered
        // TODO add your handling code here:
         /**
     * Listener untuk label "Buat Akun" di panel login.
     * Berpindah ke frame registrasi.
     *
     * @param evt Event klik mouse
     */
       labelAkun.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_labelAkunMouseEntered

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed
        // TODO add your handling code here:
         /**
     * Listener untuk checkbox tampilkan password saat registrasi.
     * Menampilkan atau menyembunyikan karakter password.
     *
     * @param evt Event checkbox berubah
     */

        String username = Isinama.getText();
        String password = new String(Isipass.getPassword());
        String selectedRole = role.getSelectedItem().toString();

        // Validasi input
        if (username.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Username dan Password tidak boleh kosong!");
            return;
        }

        if (password.length() > 10) {
            JOptionPane.showMessageDialog(this, "Password maksimal 10 karakter.");
            return;
        }

        if (selectedRole.equalsIgnoreCase("masuk sebagai")) {
            JOptionPane.showMessageDialog(this, "Silakan pilih peran terlebih dahulu!");
            return;
        }

        // Cek admin
        if (selectedRole.equalsIgnoreCase("admin")) {
            if (username.equals("admin") && password.equals("admin123")) {
                JOptionPane.showMessageDialog(this, "Login berhasil sebagai Admin");

                // Pastikan class Admin kamu extends JFrame dan ada initComponents()
                new AdminFrame().setVisible(true);
                this.dispose();

            } else {
                JOptionPane.showMessageDialog(this, "Username atau password admin salah!");
            }
            return;
        }

        // Cek user dari database
        if (selectedRole.equalsIgnoreCase("user")) {
            try (Connection conn = koneksi.getConnection()) {
                String sql = "SELECT * FROM user WHERE username=? AND password=?";
                PreparedStatement stmt = conn.prepareStatement(sql);
                stmt.setString(1, username);
                stmt.setString(2, password);

                ResultSet rs = stmt.executeQuery();
                if (rs.next()) {
                    JOptionPane.showMessageDialog(this, "Login berhasil sebagai User!");
                    JOptionPane.showMessageDialog(this, "Selamat Datang " + username);
                    new TampilanAwal().setVisible(true);
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Username atau password salah!", "Login Gagal", JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Terjadi Kesalahan Database", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }

    }//GEN-LAST:event_LoginActionPerformed

    private void BalikKeRegisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BalikKeRegisMouseClicked
        // TODO add your handling code here:
        /**
     * Mengubah kursor menjadi tangan saat mouse hover di label "Buat Akun".
     *
     * @param evt Event mouse masuk
     */
        this.dispose();
        new RegistFrame().setVisible(true);
    }//GEN-LAST:event_BalikKeRegisMouseClicked

    private void BalikKeRegisMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BalikKeRegisMouseEntered
        // TODO add your handling code here:
        /**
     * Fungsi utama program.
     * Menjalankan RegistFrame sebagai tampilan awal aplikasi.
     *
     * @param args Argumen baris perintah (tidak digunakan)
     */
        BalikKeRegis.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_BalikKeRegisMouseEntered

    private void tampilPassword11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tampilPassword11ActionPerformed
        // TODO add your handling code here:
        /**
     * Listener untuk checkbox tampilkan password saat login.
     * Menampilkan atau menyembunyikan karakter password.
     *
     * @param evt Event checkbox berubah
     */
        if (tampilPassword1.isSelected()) {
            Isipass.setEchoChar((char) 0);
        } else {
            Isipass.setEchoChar('*');

        }
    }//GEN-LAST:event_tampilPassword11ActionPerformed

    private void IsipassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IsipassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IsipassActionPerformed

    private void IsinamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IsinamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IsinamaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    

    java.awt.EventQueue.invokeLater(new Runnable() {
        @Override
        public void run() {
              new RegistFrame().setVisible(true);
    }
        
   
    });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BalikKeRegis;
    private javax.swing.JTextField Isinama;
    private javax.swing.JPasswordField Isipass;
    private javax.swing.JButton Login;
    private javax.swing.JLabel Title;
    private javax.swing.JTextField inputNama;
    private javax.swing.JPasswordField inputPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel labelAkun;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JLabel registNama;
    private javax.swing.JComboBox<String> role;
    private javax.swing.JCheckBox tampilPassword;
    private javax.swing.JCheckBox tampilPassword1;
    private javax.swing.JButton tombolOke;
    // End of variables declaration//GEN-END:variables
}
